version: '3'
services:
  tf:
    build: ./terraform
    tty: true
    working_dir: /terraform
    volumes:
      - "./terraform/src:/terraform"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
