version: '3'
services:
  grafana:
    build: ./grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
  influx:
    build: ./influx
    ports:
      - "8086:8086"
    volumes:
      - ./influx/data:/var/lib/influxdb
  telegraf:
    build: ./telegraf
    depends_on:
      - influx
  # capacitor:
  #   build: ./capacitor
