version: '3'
services:
  app:
    build: ./bff
    tty: true
    working_dir: /go/src/github.com/blacknikka/kinesis-iot
    volumes:
      - "./bff/src:/go/src/github.com/blacknikka/kinesis-iot"
    environment:
      IOT_ENDPOINT: ${IOT_ENDPOINT}
    ports:
      - 8080:8080
  db:
    build: ./bff/db
    volumes:
      - "./bff/db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  mongo:
    image: mongo
    volumes:
      - "./bff/mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
