version: '3'
services:
  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile.local
    tty: true
    working_dir: /go/src/github.com/blacknikka/kinesis-iot
    volumes:
      - "./bff/src:/go/src/github.com/blacknikka/kinesis-iot"
    environment:
      CLUSTER_ENDPOINT: ${CLUSTER_ENDPOINT}
      CLUSTER_USERNAME: ${CLUSTER_USERNAME}
      CLUSTER_PASSWORD: ${CLUSTER_PASSWORD}
      CLUSTER_OPTIONS: ${CLUSTER_OPTIONS}
      DATABSE_NAME: ${DATABSE_NAME}
      NORMAL_COLLECTION: ${NORMAL_COLLECTION}
      SUMMARY_COLLECTION: ${SUMMARY_COLLECTION}
    ports:
      - 8080:8080
  mongo:
    image: mongo
    volumes:
      - "./bff/mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  front:
    build: ./front/
    tty: true
    volumes:
      - ./front/src:/app
      - ./front/yarn-cache:/usr/local/share/.cache/yarn/v2
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_ENDPOINT: ${REACT_APP_BACKEND_ENDPOINT}

